# install pytorch 2.1.0
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

# pytorch 버전 재설치
RUN pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117

# Install OpenMMLab Toolkits as Python packages
RUN pip install -U openmim
RUN mim install mmengine "mmcv>=2.0.0" "mmpretrain>=1.0.0rc7" "mmsegmentation>=1.2.2" "mmdet>=3.0.0"
# RUN mim install mmengine==0.10.4 mmcv==2.1.0 mmpretrain==1.2.0
# RUN pip install mmsegmentation==1.2.2 mmdet==3.3.0

# Install Open-cd
RUN apt update && apt-get update
RUN apt-get update --fix-missing
RUN pip install --upgrade pip
RUN printf "6\n69" | apt install -y software-properties-common

RUN apt install -y git
WORKDIR /root
RUN git clone https://github.com/likyoo/open-cd.git
WORKDIR ./open-cd
RUN pip install -v -e .

# Install GDAL in conda
RUN apt install -y git libglib2.0-0 libgl1-mesa-glx build-essential geotiff-bin libgdal-dev
RUN conda update -y -n base -c defaults conda
RUN conda install -y -c conda-forge libgdal gdal --solver classic
RUN conda install -y poppler

# Install other dependencies
RUN pip install ftfy regex rasterio geopandas
RUN apt install -y libgl1-mesa-glx
RUN apt-get install -y libglib2.0-0

# Activate conda
RUN conda init --all
RUN /bin/bash -c "source activate base"