FROM pytorch/pytorch:2.4.1-cuda12.1-cudnn9-devel

ENV DEBIAN_FRONTEND=noninteractive \
    PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ gcc git \
        gdal-bin libgdal-dev \
        libgl1 libglib2.0-0 && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt /tmp/requirements-building.txt
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r /tmp/requirements-building.txt

COPY workspace/ /workspace/

CMD ["python", "/workspace/main.py"]
