FROM python:3.10-slim

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    g++ gcc libgdal-dev gdal-bin python3-dev \
    libgl1 libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "main.py"]
