version: '3.9'

services:
  dt:
    image: dt:latest
    volumes:
      - ./workspace:/workspace
    shm_size: '50gb'
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - FORCE_COLOR=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: sh -c "python /workspace/main.py --input ${dataset_path} --output ${output_path} --model ${model_path}"

